/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class BatteryCapacity : Message
    {
        public const string RosMessageName = "mobile_base_driver/BatteryCapacity";

        public short mAh { get; set; }
        public sbyte pct { get; set; }
        public sbyte rounded_pct { get; set; }
        //  capacity percentage estimate, rounded to the nearest 5 and
        //  subjected to hysteresis so it can only change if the value has
        //  changed by at least 5

        public BatteryCapacity()
        {
            this.mAh = 0;
            this.pct = 0;
            this.rounded_pct = 0;
        }

        public BatteryCapacity(short mAh, sbyte pct, sbyte rounded_pct)
        {
            this.mAh = mAh;
            this.pct = pct;
            this.rounded_pct = rounded_pct;
        }
    }
}
