/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class Bumper : Message
    {
        public const string RosMessageName = "mobile_base_driver/Bumper";

        //  Provides a bumper stae
        //  bumper
        public const byte RIGHT = 0;
        public const byte CENTER = 1;
        public const byte LEFT = 2;
        //  bumper state
        public const byte RELEASED = 0;
        public const byte PRESSED = 1;
        public byte bumper { get; set; }
        public byte state { get; set; }

        public Bumper()
        {
            this.bumper = 0;
            this.state = 0;
        }

        public Bumper(byte bumper, byte state)
        {
            this.bumper = bumper;
            this.state = state;
        }
    }
}
