/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class ChestLeds : Message
    {
        public const string RosMessageName = "mobile_base_driver/ChestLeds";

        //  Provide chest LEDs frame
        //  Index 0 is the center LED
        //  With 0 degrees straight up increasing clockwise
        //  Inner ring
        //  Index 1 : 150 degrees
        //  Index 2 : 210 degrees
        //  Index 3 : 270 degrees
        //  Index 4 : 330 degrees
        //  Index 5 : 30 degrees
        //  Index 6 : 90 degrees
        //  Outter ring
        //  Index 13 : 22 degrees
        //  Index 14 : 67 degrees
        //  Index 7  : 112 degrees
        //  Index 8  : 157 degrees
        //  Index 9  : 202 degrees
        //  Index 10 : 247 degrees
        //  Index 11 : 292 degrees
        //  Index 12 : 337 degrees
        public Led[] leds { get; set; }

        public ChestLeds()
        {
            this.leds = new Led[15];
        }

        public ChestLeds(Led[] leds)
        {
            this.leds = leds;
        }
    }
}
