/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class CliffSensor : Message
    {
        public const string RosMessageName = "mobile_base_driver/CliffSensor";

        //  Provides a cliff sensor reading
        //  This message is generated whenever a particular cliff sensor signals that the
        //  robot approaches or moves away from a cliff.
        //  cliff sensor
        public const byte RIGHT = 0;
        public const byte MIDRIGHT = 1;
        public const byte MIDLEFT = 2;
        public const byte LEFT = 3;
        public const byte BACKLEFT = 4;
        public const byte BACKRIGHT = 5;
        //  cliff sensor state
        public const byte FLOOR = 0;
        public const byte CLIFF = 1;
        public byte sensor { get; set; }
        public byte state { get; set; }
        //  distance to floor when cliff was detected
        public float distance { get; set; }
        //  return rate from the vl6180x, rear cliff sensors only
        public float return_rate { get; set; }

        public CliffSensor()
        {
            this.sensor = 0;
            this.state = 0;
            this.distance = 0.0f;
            this.return_rate = 0.0f;
        }

        public CliffSensor(byte sensor, byte state, float distance, float return_rate)
        {
            this.sensor = sensor;
            this.state = state;
            this.distance = distance;
            this.return_rate = return_rate;
        }
    }
}
