/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class CliffArray : Message
    {
        public const string RosMessageName = "mobile_base_driver/CliffArray";

        public Header header { get; set; }
        //  XXX: sensor indices in their respective arrays does not necessarily
        //  reflect what sensor it actually represents
        //  Each of these messages has its own internal field for that purpose.
        //  Example: check wheeldrop[0].wheel == WheelDrop.RIGHT and do not rely on the 0
        public CliffSensor[] cliff { get; set; }

        public CliffArray()
        {
            this.header = new Header();
            this.cliff = new CliffSensor[0];
        }

        public CliffArray(Header header, CliffSensor[] cliff)
        {
            this.header = header;
            this.cliff = cliff;
        }
    }
}
