/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class Clothesline : Message
    {
        public const string RosMessageName = "mobile_base_driver/Clothesline";

        //  clothesline sensor state
        public const byte NOTHING = 0;
        public const byte SOMETHING = 1;
        public byte state { get; set; }
        public float distance { get; set; }

        public Clothesline()
        {
            this.state = 0;
            this.distance = 0.0f;
        }

        public Clothesline(byte state, float distance)
        {
            this.state = state;
            this.distance = distance;
        }
    }
}
