/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class Led : Message
    {
        public const string RosMessageName = "mobile_base_driver/Led";

        //  Provides a three color LED state
        public byte red { get; set; }
        public byte green { get; set; }
        public byte blue { get; set; }

        public Led()
        {
            this.red = 0;
            this.green = 0;
            this.blue = 0;
        }

        public Led(byte red, byte green, byte blue)
        {
            this.red = red;
            this.green = green;
            this.blue = blue;
        }
    }
}
