/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class Motor : Message
    {
        public const string RosMessageName = "mobile_base_driver/Motor";

        //  Provides a motor state
        //  motor
        public const byte RIGHTWHEEL = 0;
        public const byte LEFTWHEEL = 1;
        public const byte PAN = 2;
        public const byte TILT = 3;
        public const byte EYES = 4;
        public bool stalled { get; set; }
        public bool pushed { get; set; }

        public Motor()
        {
            this.stalled = false;
            this.pushed = false;
        }

        public Motor(bool stalled, bool pushed)
        {
            this.stalled = stalled;
            this.pushed = pushed;
        }
    }
}
