/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class Power : Message
    {
        public const string RosMessageName = "mobile_base_driver/Power";

        public ushort[] adc_channels { get; set; }
        public float v_dock { get; set; }
        public float v_batt { get; set; }
        public float i_batt { get; set; }
        public float t_batt { get; set; }
        public bool dock_present { get; set; }
        public bool is_charging { get; set; }
        public bool power_button_pressed { get; set; }
        public BatteryCapacity battery { get; set; }

        public Power()
        {
            this.adc_channels = new ushort[0];
            this.v_dock = 0.0f;
            this.v_batt = 0.0f;
            this.i_batt = 0.0f;
            this.t_batt = 0.0f;
            this.dock_present = false;
            this.is_charging = false;
            this.power_button_pressed = false;
            this.battery = new BatteryCapacity();
        }

        public Power(ushort[] adc_channels, float v_dock, float v_batt, float i_batt, float t_batt, bool dock_present, bool is_charging, bool power_button_pressed, BatteryCapacity battery)
        {
            this.adc_channels = adc_channels;
            this.v_dock = v_dock;
            this.v_batt = v_batt;
            this.i_batt = i_batt;
            this.t_batt = t_batt;
            this.dock_present = dock_present;
            this.is_charging = is_charging;
            this.power_button_pressed = power_button_pressed;
            this.battery = battery;
        }
    }
}
