/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class SafetyStatus : Message
    {
        public const string RosMessageName = "mobile_base_driver/SafetyStatus";

        //  bit positions, same as in iris_comm
        public const sbyte HB_bp = 0; //  Heartbeat
        public const sbyte CFHW_bp = 1; //  Cliff to Motor Control HW
        public const sbyte CF0_bp = 2; //  Cliff 0
        public const sbyte CF1_bp = 3; //  Cliff 1
        public const sbyte CF2_bp = 4; //  Cliff 2
        public const sbyte CF3_bp = 5; //  Cliff 3
        public const sbyte CF4_bp = 6; //  Cliff 4
        public const sbyte CF5_bp = 7; //  Cliff 5
        public const sbyte DP_bp = 8; //  Drop Right and Left
        public const sbyte BPR_bp = 10; //  Bump Right
        public const sbyte BPM_bp = 11; //  Bump Middle
        public const sbyte BPL_bp = 12; //  Bump Left
        public const sbyte CLL_bp = 13; //  Clothesline
        public uint status { get; set; }

        public SafetyStatus()
        {
            this.status = 0;
        }

        public SafetyStatus(uint status)
        {
            this.status = status;
        }
    }
}
