/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class Sensors : Message
    {
        public const string RosMessageName = "mobile_base_driver/Sensors";

        //  sensor state published at a fixed frequency by the driver
        public Header header { get; set; }
        //  XXX: sensor indices in their respective arrays does not necessarily
        //  reflect what sensor it actually represents
        //  Each of these messages has its own internal field for that purpose.
        //  Example: check wheeldrop[0].wheel == WheelDrop.RIGHT and do not rely on the 0
        public Bumper[] bumper { get; set; }
        public WheelDrop[] wheeldrop { get; set; }
        public Touch touch { get; set; }

        public Sensors()
        {
            this.header = new Header();
            this.bumper = new Bumper[3];
            this.wheeldrop = new WheelDrop[2];
            this.touch = new Touch();
        }

        public Sensors(Header header, Bumper[] bumper, WheelDrop[] wheeldrop, Touch touch)
        {
            this.header = header;
            this.bumper = bumper;
            this.wheeldrop = wheeldrop;
            this.touch = touch;
        }
    }
}
