/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class Stall : Message
    {
        public const string RosMessageName = "mobile_base_driver/Stall";

        //  Motor Stall state published at a fixed frequency by the driver
        public Header header { get; set; }
        //  XXX: wheel indices in their respective arrays does not necessarily
        //  reflect what wheel it actually represents
        //  Each of these messages has its own internal field for that purpose.
        //  Example: check motor[0].motor == Motor.RIGHTWHEEL and do not rely on the 0
        public Motor[] motor { get; set; }

        public Stall()
        {
            this.header = new Header();
            this.motor = new Motor[5];
        }

        public Stall(Header header, Motor[] motor)
        {
            this.header = header;
            this.motor = motor;
        }
    }
}
