/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class Telescope : Message
    {
        public const string RosMessageName = "mobile_base_driver/Telescope";

        public Header header { get; set; }
        public bool front_noise { get; set; }
        public bool front_left { get; set; }
        public bool front_right { get; set; }
        public bool front_middle { get; set; }
        public bool back_noise { get; set; }
        public bool back_left { get; set; }
        public bool back_right { get; set; }
        public bool back_middle { get; set; }

        public Telescope()
        {
            this.header = new Header();
            this.front_noise = false;
            this.front_left = false;
            this.front_right = false;
            this.front_middle = false;
            this.back_noise = false;
            this.back_left = false;
            this.back_right = false;
            this.back_middle = false;
        }

        public Telescope(Header header, bool front_noise, bool front_left, bool front_right, bool front_middle, bool back_noise, bool back_left, bool back_right, bool back_middle)
        {
            this.header = header;
            this.front_noise = front_noise;
            this.front_left = front_left;
            this.front_right = front_right;
            this.front_middle = front_middle;
            this.back_noise = back_noise;
            this.back_left = back_left;
            this.back_right = back_right;
            this.back_middle = back_middle;
        }
    }
}
