/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class Touch : Message
    {
        public const string RosMessageName = "mobile_base_driver/Touch";

        //  true means touched
        //  [FRONT_LEFT, LEFT, REAR_LEFT, CENTER, FRONT, REAR_RIGHT, RIGHT, FRONT_RIGHT]
        public bool[] electrodes { get; set; }

        public Touch()
        {
            this.electrodes = new bool[0];
        }

        public Touch(bool[] electrodes)
        {
            this.electrodes = electrodes;
        }
    }
}
