/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.MobileBaseDriver
{
    public class WheelTrajPoint : Message
    {
        public const string RosMessageName = "mobile_base_driver/WheelTrajPoint";

        public Duration time_from_start { get; set; }
        public double linear_vel { get; set; }
        public double angular_vel { get; set; }

        public WheelTrajPoint()
        {
            this.time_from_start = new Duration();
            this.linear_vel = 0.0;
            this.angular_vel = 0.0;
        }

        public WheelTrajPoint(Duration time_from_start, double linear_vel, double angular_vel)
        {
            this.time_from_start = time_from_start;
            this.linear_vel = linear_vel;
            this.angular_vel = angular_vel;
        }
    }
}
